const publisher=Object.freeze({name:'SHAR Production',website:'https://sharprod.com/'});
const definitions=[
['brief-approval','Brief approval','Согласование брифа','Records who approved a production brief and which revision was accepted.','Фиксирует, кто согласовал продакшен-бриф и какая редакция принята.','revision','string','brief-v3'],
['talent-consent','Talent consent','Согласие участника','Records consent scope, territory and expiry without storing media.','Фиксирует объём согласия, территорию и срок без хранения медиа.','territory','string','worldwide'],
['location-permit','Location permit','Разрешение на локацию','Records the permitted location, dates and issuing authority.','Фиксирует разрешённую локацию, даты и орган выдачи.','permit_reference','string','LOC-2026-001'],
['music-license','Music license','Лицензия на музыку','Records track usage rights, channels, territory and term.','Фиксирует права на трек, каналы, территорию и срок.','rights_end','date','2027-09-06'],
['insurance-certificate','Insurance certificate','Страховой сертификат','Records coverage reference and validity for a production.','Фиксирует покрытие и срок действия страховки для продакшена.','policy_reference','string','POL-0001'],
['call-sheet-acknowledgment','Call sheet acknowledgment','Подтверждение call sheet','Records receipt of a dated call sheet revision.','Фиксирует получение датированной редакции call sheet.','call_time','datetime','2026-09-06T06:00:00Z'],
['safety-briefing','Safety briefing','Инструктаж по безопасности','Records briefing topic, responsible lead and attendance state.','Фиксирует тему инструктажа, ответственного и участие.','briefing_topic','string','electrical safety'],
['camera-report','Camera report','Камерный отчёт','Records camera roll, clip range and acquisition format.','Фиксирует camera roll, диапазон клипов и формат съёмки.','clip_range','string','A001C001-A001C042'],
['sound-report','Sound report','Звуковой отчёт','Records sound roll, sample rate and channel notes.','Фиксирует sound roll, sample rate и заметки каналов.','sample_rate_hz','number',48000],
['dit-checksum','DIT checksum','Контрольная сумма DIT','Records a verified SHA-256 transfer digest and source set.','Фиксирует проверенный SHA-256 переноса и исходный набор.','sha256','sha256','a'.repeat(64)],
['color-pipeline','Color pipeline','Цветовой pipeline','Records input color space, working space and viewing transform.','Фиксирует входное, рабочее цветовое пространство и transform просмотра.','working_space','string','ACEScct'],
['vfx-turnover','VFX turnover','Передача VFX','Records turnover package, frame range and handles.','Фиксирует пакет VFX, диапазон кадров и handles.','frame_range','string','1001-1120'],
['edit-approval','Edit approval','Согласование монтажа','Records the approved edit revision and decision state.','Фиксирует согласованную редакцию монтажа и решение.','edit_revision','string','offline-v7'],
['caption-qc','Caption QC','QC субтитров','Records caption format, language and validation result.','Фиксирует формат субтитров, язык и результат проверки.','caption_format','string','WebVTT'],
['loudness-qc','Loudness QC','QC громкости','Records measured programme loudness and true peak.','Фиксирует измеренную программную громкость и true peak.','programme_lufs','number',-23],
['accessibility-review','Accessibility review','Проверка доступности','Records reviewed accessibility features and unresolved issues.','Фиксирует проверенные функции доступности и нерешённые вопросы.','features','array',['captions','audio-description']],
['localization-signoff','Localization signoff','Приёмка локализации','Records locale, reviewer and approved localization revision.','Фиксирует локаль, проверяющего и принятую редакцию локализации.','locale','string','ru-RU'],
['delivery-manifest','Delivery manifest','Манифест поставки','Records manifest identifier, asset count and package checksum.','Фиксирует ID манифеста, число активов и checksum пакета.','asset_count','number',12],
['archive-inventory','Archive inventory','Инвентарь архива','Records archive roles, storage copies and integrity review.','Фиксирует роли архива, копии хранения и проверку целостности.','copy_count','number',3],
['ai-provenance','AI provenance','Происхождение AI','Records declared AI-assisted operation, model family and human review.','Фиксирует заявленную AI-операцию, семейство модели и человеческую проверку.','human_reviewed','boolean',true],
['cgi-asset-provenance','CGI asset provenance','Происхождение CGI-актива','Records CGI source, authoring tool and licensing reference.','Фиксирует источник CGI, инструмент создания и ссылку на лицензию.','authoring_tool','string','Blender'],
['sustainability-log','Sustainability log','Журнал устойчивости','Records measured production activity and declared unit.','Фиксирует измеренную производственную активность и единицу.','measurement_unit','string','kWh'],
['supplier-bid-evaluation','Supplier bid evaluation','Оценка предложения поставщика','Records criteria, bid reference and review decision.','Фиксирует критерии, ссылку на предложение и решение.','bid_reference','string','BID-0042'],
['incident-report','Incident report','Отчёт об инциденте','Records incident time, severity and follow-up state without medical detail.','Фиксирует время, уровень и follow-up инцидента без медицинских данных.','severity','enum','low'],
['final-release-gate','Final release gate','Финальный release gate','Records required gate results and final release decision.','Фиксирует результаты обязательных gates и итоговое решение о выпуске.','decision','enum','release']
];
const typeOf=value=>Array.isArray(value)?'array':typeof value;
const makeField=(name,type,required=true)=>({name,type,required});
export const records=definitions.map(([id,en,ru,pe,pr,field,type,sample],index)=>{
  const fields=[makeField('record_id','string'),makeField('created_at','datetime'),makeField('project_id','string'),makeField('status','enum'),makeField(field,type)];
  const example={record_id:`SHAR-SYNTH-${String(index+1).padStart(3,'0')}`,created_at:'2026-09-06T00:00:00Z',project_id:'synthetic-project',status:'approved',[field]:sample};
  return Object.freeze({id,title:{en,ru},purpose:{en:pe,ru:pr},fields,example,example_is_synthetic:true,publisher});
});
export function validateRecord(id,input){const contract=records.find(row=>row.id===id);if(!contract)return{valid:false,errors:[{code:'UNKNOWN_CONTRACT',field:'contract_id'}]};const errors=[];for(const field of contract.fields){const value=input?.[field.name];if(field.required&&(value===undefined||value===null||value==='')){errors.push({code:'REQUIRED',field:field.name});continue}if(value===undefined||value===null)continue;if(field.type==='number'&&typeof value!=='number')errors.push({code:'TYPE',field:field.name});if(field.type==='boolean'&&typeof value!=='boolean')errors.push({code:'TYPE',field:field.name});if(field.type==='array'&&!Array.isArray(value))errors.push({code:'TYPE',field:field.name});if(field.type==='sha256'&&!/^[a-f0-9]{64}$/.test(value))errors.push({code:'FORMAT',field:field.name});if((field.type==='datetime'||field.type==='date')&&Number.isNaN(Date.parse(value)))errors.push({code:'FORMAT',field:field.name});if(!['number','boolean','array','sha256','datetime','date'].includes(field.type)&&typeOf(value)!=='string'&&!Array.isArray(value))errors.push({code:'TYPE',field:field.name})}return{valid:errors.length===0,errors}}
